version: '3.5'
services:
  app:
    build:
      context: .docker
      dockerfile: web.Dockerfile
    ports:
      - "80:80"
    volumes:
      - ./:/var/www/html
    environment:
      - key=qwerty
  npm:
    image: mhart/alpine-node:10.16.3
    command: sh -c 'npm install && npm run watch'
    volumes:
      - .:/app
    working_dir: /app
  database:
    image: mariadb:10.2        
    environment:
      MYSQL_DATABASE: 'test'
      MYSQL_USER: 'test'
      MYSQL_PASSWORD: 'qwerty'
      MYSQL_ROOT_PASSWORD: 'qwerty'
    ports:
      - '3306:3306'
    expose:
      - '3306'
